# Generated by Django 3.1.1 on 2021-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('climate', models.CharField(max_length=60)),
                ('world', models.CharField(max_length=60)),
                ('work', models.CharField(max_length=60)),
                ('medicine', models.CharField(max_length=60)),
                ('citizenship', models.CharField(max_length=60)),
            ],
        ),
    ]
